title: root💀sonofabot-sec:~#
description: I scan, I map, I exploit .... Ghost in your shell
 Try Harder!!!
show_downloads: false
show_repo: false
theme: jekyll-theme-hacker

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
